### ISSUE TITLE
Формат события в описании

### ISSUE THREAD

**Issue by mbelsky** [web-standards-ru/calendar-bot#12]
Привет,

У событий в телеграм канале не отображается формат. Как вам идея для онлайн событий дописывать `(онлайн)` к названию события? Так уже делается в календаре: https://github.com/web-standards-ru/calendar/pull/527

**Comment by pepelsbey** [comment]
Было бы круто :)

**Comment by dmitriym09** [comment]
> Было бы круто :)

Добавлю и сделаю pull request
